# The config file that will take the values from the PS4 joystick
# and publish to the topics: steering and throttling.
# 

teleop:
  # Enable Human control by holding Left Bumper
  human_control:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: ackermann_cmd_mux/input/human_driver
#    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: drive.speed
        scale: 1.0                   # joystick will command plus or minus 2 meters / second
        offset: 0.0
      -
        axis: 2
        target: drive.steering_angle
        scale: 0.51                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0

  start_recording:
    type: service
    service_name: /record_topics
    service_request:
      name: recorder
      topics: [/low_level/ackermann_cmd_mux/input/teleop,/raspicam_node/image/compressed]
    buttons: [0,4]
    service_persistent: False

  stop_recording:
    type: service
    service_name: /stop_recording
    service_request:
      name: recorder
    buttons: [1,4]
    service_persistent: False


#   throttling:
#     type: topic
#     message_type: std_msgs/Float64
#     topic_name: throttling
#     axis_mappings:
#       -
#         axis: 1
#         target: data

#   steering:
#     type: topic
#     message_type: std_msgs/Float64
#     topic_name: steering
#     axis_mappings:
#       -
#         axis: 2
#         target: data

